services:
  - type: web
    name: machine-shop-website-backend
    env: node
    buildCommand: |
      npm install
      cd server && npm install
      cd ..
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    healthCheckPath: /api/health