services:
  - type: web
    name: machine-shop-website
    env: node
    buildCommand: |
      npm install
      cd server && npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001